export const SAMPLE_NAMES: string[] = [
  "Ansil Hashim",
  "Dr. Alexander Bartholomew Montgomery III",
  "Sophia Isabella Rodriguez-Martinez",
  "Muhammed Al-Mansoor",
  "Elena Rostova",
  "Christopher Bennett",
  "Samantha Jane Watson",
  "Takashi Yamamoto",
  "Chidimma Okonkwo",
  "Guillaume de La Tour",
  "Aarav Patel",
  "Priya Sharma",
  "Benjamin Franklin Sterling",
  "Amara Van Der Bilt",
  "Gabriel Santos-Silva",
  "Fatima Zahra El-Amrani",
  "Liam O'Connor",
  "Isabella Grace D'Angelo",
  "Kwame Mensah",
  "Zoe Chen",
  "Dmitri Ivanov",
  "Mei-Ling Huang",
  "Lucas Vance",
  "Charlotte Bronte Highsmith",
  "Siddharth Narayan",
  "Freja Lindqvist",
  "Mateo Rossi",
  "Amina Abdullahi",
  "Ethan Hunt",
  "Anastasia Nikolaeva",
  "Oliver James Radcliffe",
  "Victoria Elizabeth Windsor",
  "Rohan Deshmukh",
  "Yuki Takahashi",
  "Nia Campbell",
  "Santiago Fernandez",
  "Beatriz Morales",
  "Kasper Johansen",
  "Deepika Padukone",
  "Arthur Pendelton-Smith",
  "Layla Al-Mansouri",
  "Thao Nguyen",
  "Sebastian Von Hapsburg",
  "Ingrid Bergman",
  "Kobe Bryant",
  "Seraphina Rose Dupont",
  "Tariq Mahmood",
  "Xavier Hernandez",
  "Chiara Ferragni",
  "Hiroshi Tanaka",
  "Zainab Bibi",
  "Julian Casablancas",
  "Camila Cabello",
  "Marcus Aurelius Antoninus",
  "Nora Al-Thani",
  "Sora Kim",
  "Lukas Podolski",
  "Valerie St. Clair",
  "Gautam Gambhir",
  "Farida Jalal",
  "Derrick Rose",
  "Aurelia Vance",
  "Dominic Toretto",
  "Kavita Krishnamurthy",
  "Kenji Sato",
  "Noor Al-Hassan",
  "Felipe Masa",
  "Hannah Abbott",
  "Gabriel Macht",
  "Lina Ben Mhenni",
  "Viktor Krum",
  "Amelia Earhart",
  "Charles Xavier",
  "Fatima Al-Fihri",
  "George Washington Carver",
  "Harriet Tubman",
  "Idris Elba",
  "Jacqueline Kennedy Onassis",
  "Kailash Satyarthi",
  "Leonardo da Vinci",
  "Marie Skłodowska-Curie",
  "Nelson Rolihlahla Mandela",
  "Oscar Wilde",
  "Pablo Ruiz Picasso",
  "Queen Elizabeth II",
  "Rabindranath Tagore",
  "Stephen William Hawking",
  "Tim Berners-Lee",
  "Ursula K. Le Guin",
  "Vincent Willem van Gogh",
  "Winston Leonard Spencer-Churchill",
  "Xenia Onatopp",
  "Yuri Alekseyevich Gagarin",
  "Zaha Mohammad Hadid",
  "Ada Lovelace",
  "Alan Mathison Turing",
  "Albert Einstein",
  "Alexander Graham Bell",
  "Alfred Bernhard Nobel",
  "Aristotle",
  "Benjamin Franklin",
  "Blaise Pascal",
  "Carl Friedrich Gauss",
  "Charles Robert Darwin",
  "Dmitri Mendeleev",
  "Erwin Schrödinger",
  "Galileo Galilei",
  "Gottfried Wilhelm Leibniz",
  "Isaac Newton",
  "James Clerk Maxwell",
  "Johannes Kepler",
  "Louis Pasteur",
  "Michael Faraday",
  "Nikola Tesla",
  "Niels Henrik David Bohr",
  "Pierre-Simon Laplace",
  "René Descartes",
  "Richard Phillips Feynman",
  "Robert Hooke",
  "Rosalind Elsie Franklin",
  "Sigmund Freud",
  "Thomas Alva Edison",
  "Werner Karl Heisenberg",
  "Wilhelm Conrad Röntgen",
  "Abigail Adams",
  "Alexander Hamilton",
  "Andrew Jackson",
  "Abraham Lincoln",
  "Barack Hussein Obama",
  "Dwight David Eisenhower",
  "Franklin Delano Roosevelt",
  "George Washington",
  "Harry S. Truman",
  "John Fitzgerald Kennedy",
  "Thomas Jefferson",
  "Woodrow Wilson",
  "Auguste Rodin",
  "Claude Monet",
  "Diego Rivera",
  "Edgar Degas",
  "Frida Kahlo",
  "Georgia O'Keeffe",
  "Henri Matisse",
  "Jackson Pollock",
  "Johannes Vermeer",
  "Katsushika Hokusai",
  "Michelangelo Buonarroti",
  "Paul Cézanne",
  "Rembrandt van Rijn",
  "Salvador Dalí",
  "Sandro Botticelli",
  "Wassily Kandinsky",
  "Agatha Christie",
  "Aldous Huxley",
  "Arthur Conan Doyle",
  "Edgar Allan Poe",
  "Ernest Miller Hemingway",
  "Franz Kafka",
  "Gabriel García Márquez",
  "George Orwell",
  "Homer",
  "Jane Austen",
  "Johann Wolfgang von Goethe",
  "John Milton",
  "Leo Tolstoy",
  "Mark Twain",
  "Mary Wollstonecraft Shelley",
  "Miguel de Cervantes",
  "Fyodor Dostoevsky",
  "Virginia Woolf",
  "William Shakespeare",
  "Wolfgang Amadeus Mozart",
  "Ludwig van Beethoven",
  "Johann Sebastian Bach",
  "Frederic Chopin",
  "Pyotr Ilyich Tchaikovsky",
  "Franz Liszt",
  "Antonio Vivaldi",
  "Giuseppe Verdi",
  "Richard Wagner",
  "Claude Debussy",
  "Igor Stravinsky",
  "Sergei Rachmaninoff",
  "Béla Bartók",
  "Clara Schumann",
  "Fanny Mendelssohn",
  "Gustav Mahler",
  "Jean Sibelius",
  "Maurice Ravel",
  "Modest Mussorgsky",
  "Antonio Salieri",
  "Camille Saint-Saëns",
  "Edvard Grieg",
  "Felix Mendelssohn",
  "Gabriel Fauré",
  "Hector Berlioz",
  "Niccolò Paganini",
  "Robert Schumann",
  "Sergei Prokofiev"
];
